[package]
name = "toolbox"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
