[workspace]
members = ["demo", "toolbox"]
resolver = "2"

[workspace.dependencies]
salvo = { version = "0.81.0" }
serde = { version = "1.0.219" }
serde_json = { version = "1.0.142" }
tracing = { version = "0.1.41" }
